default wrapped_es.pop() to None if key missing to avoid TB
    Failed to run scrub_pivotal.py, returned exit code 1 with output: Traceback (most recent call last):
      File "/home/taylor/git/cloudbolt/cb-dev/scrub_pivotal.py", line 47, in <module>
        name_template=NAME_TEMPLATE
      File "/usr/local/lib/python2.7/site-packages/pivotalclient/__init__.py", line 292, in create_stories_from_integration_stories
        wrapped_es.pop('requested_by_id')
    KeyError: 'requested_by_id'